services:
  spark_db:
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: spark
      POSTGRES_PASSWORD: spark
      POSTGRES_DB: spark
    ports:
      - "5432:5432"
volumes:
  postgres_data: {}
